# Generated by Django 5.1.5 on 2025-04-25 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_triparea_triplocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('photo_reference', models.CharField(blank=True, max_length=500, null=True)),
                ('types', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('trip_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_items', to='pages.triparea')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
